# Generated by Django 4.2.6 on 2023-10-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0002_menproduct_img_alter_menproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menproduct',
            name='description',
            field=models.TextField(),
        ),
    ]
