# Generated by Django 4.2.6 on 2023-10-27 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0003_alter_menproduct_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
