# Generated by Django 4.2.6 on 2023-10-29 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0008_cartitem_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='catagory',
        ),
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='e_app.catagories'),
        ),
    ]
