# Generated by Django 4.2.6 on 2023-10-29 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0009_remove_cartitem_catagory_product_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='e_app.catagories'),
        ),
    ]
