# Generated by Django 4.2.6 on 2023-10-29 06:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0011_rename_productcatagories_catagories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
